# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_size_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('crop', 'crop')], default='crop', max_length=255, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='thumbs',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Url'),
        ),
    ]
