# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170829_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbs',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='photos.Size'),
        ),
    ]
