# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170830_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='count_images',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='', verbose_name='Count of images'),
        ),
    ]
